# Dependencies
markdown:         kramdown
kramdown:
  input:          GFM
gems:

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            ÈŸ…Á
tagline:          Something
url:              http://orangeclub.github.io
paginate:         1
baseurl:          /
author:
  name:           orange club
  url:            
  email:          ayame9joe@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/orangeclub/orangeclub.github.io
