# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            橘社
tagline:          受命不迁，有以自乐
url:              https://orangeclub.github.io
paginate:         1
baseurl:          https://orangeclub.github.io
author:
  name:           
  url:            https://orangeclub.github.io
  email:          ayame9joe@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/orangeclub/orangeclub.github.io



